In [1]:
from ultralytics import YOLO

# Load a model
# model = YOLO("yolo11m-pose.pt")  # load an official model
model = YOLO("yolo11n-pose.pt")  # load a custom model


/home/viplab/miniconda3/envs/videomae2/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


100%|██████████| 5.97M/5.97M [00:00<00:00, 115MB/s]


In [2]:
# results = model("/media/viplab/Storage1/driver_action_recognition/crop_new/cut_frames_rear/class_9/user_id_36305/Rear_view_user_id_36305_3_8947.jpg")  # predict on an image
results = model("/media/viplab/Storage1/driver_action_recognition/crop_new/cut_frames_rear/class_0/user_id_53307/Rear_view_user_id_53307_7_4471.jpg")


image 1/1 /media/viplab/Storage1/driver_action_recognition/crop_new/cut_frames_rear/class_0/user_id_53307/Rear_view_user_id_53307_7_4471.jpg: 640x640 1 person, 25.7ms
Speed: 6.6ms preprocess, 25.7ms inference, 28.6ms postprocess per image at shape (1, 3, 640, 640)


In [3]:
for result in results:
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    print(result.keypoints)
    probs = result.probs  # Probs object for classification outputs
    obb = result.obb  # Oriented boxes object for OBB outputs
    result.show()  # display to screen
    result.save(filename="result.jpg")  # save to disk

ultralytics.engine.results.Keypoints object with attributes:

conf: tensor([[9.9526e-01, 7.3902e-01, 9.9733e-01, 4.2246e-03, 9.9589e-01, 9.9431e-01, 9.8879e-01, 8.4267e-01, 7.1015e-01, 7.8587e-01, 7.3971e-01, 3.4196e-01, 1.9581e-01, 1.6393e-02, 8.2240e-03, 2.0659e-03, 8.8357e-04]], device='cuda:0')
data: tensor([[[2.5988e+02, 1.4759e+02, 9.9526e-01],
         [2.6646e+02, 1.2474e+02, 7.3902e-01],
         [2.3473e+02, 1.2515e+02, 9.9733e-01],
         [0.0000e+00, 0.0000e+00, 4.2246e-03],
         [1.7464e+02, 1.3259e+02, 9.9589e-01],
         [2.6667e+02, 2.5636e+02, 9.9431e-01],
         [9.9956e+01, 2.6102e+02, 9.8879e-01],
         [2.8178e+02, 4.3712e+02, 8.4267e-01],
         [1.0696e+02, 4.6254e+02, 7.1015e-01],
         [3.1402e+02, 4.1957e+02, 7.8587e-01],
         [2.6757e+02, 4.6585e+02, 7.3971e-01],
         [0.0000e+00, 0.0000e+00, 3.4196e-01],
         [0.0000e+00, 0.0000e+00, 1.9581e-01],
         [0.0000e+00, 0.0000e+00, 1.6393e-02],
         [0.0000e+00, 0.0000e+00, 8.

/usr/bin/eog: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE


In [ ]:

# Predict with the model
# results = model("/media/viplab/Storage1/driver_action_recognition/crop_new/cut_frames_side/class_9/user_id_36305/Right_side_window_user_id_36305_3_8947.jpg")  # predict on an image
results = model.track(source="/media/viplab/DATADRIVE1/driver_action_recognition/crop_videos/train/user_id_13522_5/Rear_view_user_id_13522_NoAudio_5.MP4", save=True, show=True)  # predict on an image

# Access the results
for result in results:
    xy = result.keypoints.xy  # x and y coordinates
    xyn = result.keypoints.xyn  # normalized
    kpts = result.keypoints.data  # x, y, visibility (if available)

In [8]:
results = model("/media/viplab/Storage1/driver_action_recognition/crop_new/cut_frames_side/class_9/user_id_36305/Right_side_window_user_id_36305_3_8947.jpg")  # predict on an image


image 1/1 /media/viplab/Storage1/driver_action_recognition/crop_new/cut_frames_side/class_9/user_id_36305/Right_side_window_user_id_36305_3_8947.jpg: 640x640 1 person, 19.0ms
Speed: 17.3ms preprocess, 19.0ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)


In [12]:
results[0].keypoints.xyn[0][:11]

# final_keypoints = results[0].keypoints[highest_conf_idx].xyn[0]

tensor([[0.4160, 0.6211],
        [0.0000, 0.0000],
        [0.4131, 0.6010],
        [0.0000, 0.0000],
        [0.3435, 0.5717],
        [0.2013, 0.5055],
        [0.2903, 0.7027],
        [0.2019, 0.4385],
        [0.3405, 0.9382],
        [0.0000, 0.0000],
        [0.0000, 0.0000]], device='cuda:0')

In [ ]:
import numpy as np

for result in results:
    keypoints = result.keypoints

    kpts_array = keypoints.xy if hasattr(keypoints, 'xy') else keypoints.data.cpu().numpy()

    # print(kpts_array)
    # If the keypoints object doesn't have 'xy', try 'data' attribute or convert accordingly
    # For example, if keypoints is a torch tensor:
    # kpts_array = keypoints.cpu().numpy()

    # Flatten keypoints per instance: (num_keypoints * 3)
    # If you want only (x, y), slice [:, :, :2]
    keypoint_vectors = []
    for instance_kpts in kpts_array:
        print(instance_kpts)
        # Flatten (num_keypoints, 3) -> (num_keypoints*3,)
        flattened = instance_kpts.flatten()
        keypoint_vectors.append(flattened)

    # Now keypoint_vectors is a list of 1D arrays, one per detected person/object
    # If you have multiple detections, you can select one or aggregate

    # Example: Use the first detected person's keypoints as input
    if len(keypoint_vectors) > 0:
        input_keypoints = keypoint_vectors[0]  # 1D vector for first detected person
        print("Keypoint vector shape:", input_keypoints.shape)
        # You can now concatenate this with your ResNet features for Mamba input
    else:
        print("No keypoints detected in this frame.")
    
print(keypoint_vectors)


tensor([[187.9316, 143.3364],
        [  0.0000,   0.0000],
        [175.0820, 131.1202],
        [  0.0000,   0.0000],
        [139.6472, 145.3846],
        [ 96.2096, 186.2070],
        [157.3366, 232.7977],
        [192.8087, 160.0798],
        [247.3005, 313.5802],
        [256.6579, 130.8009],
        [289.0013, 207.6659],
        [ 93.0947, 415.6727],
        [134.3389, 432.9201],
        [  0.0000,   0.0000],
        [  0.0000,   0.0000],
        [  0.0000,   0.0000],
        [  0.0000,   0.0000]], device='cuda:0')
Keypoint vector shape: torch.Size([34])
[tensor([187.9316, 143.3364,   0.0000,   0.0000, 175.0820, 131.1202,   0.0000,   0.0000, 139.6472, 145.3846,  96.2096, 186.2070, 157.3366, 232.7977, 192.8087, 160.0798, 247.3005, 313.5802, 256.6579, 130.8009, 289.0013, 207.6659,  93.0947, 415.6727, 134.3389, 432.9201,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
          0.0000,   0.0000,   0.0000], device='cuda:0')]


In [8]:
len(results)

1

In [ ]:
keypoints = results[0].keypoints

kpts_array = keypoints.xy if hasattr(keypoints, 'xy') else keypoints.data.cpu().numpy()

    # print(kpts_array)
    # If the keypoints object doesn't have 'xy', try 'data' attribute or convert accordingly
    # For example, if keypoints is a torch tensor:
    # kpts_array = keypoints.cpu().numpy()

    # Flatten keypoints per instance: (num_keypoints * 3)
    # If you want only (x, y), slice [:, :, :2]
keypoint_vectors = []
for instance_kpts in kpts_array:
    print(instance_kpts)
    # Flatten (num_keypoints, 3) -> (num_keypoints*3,)
    flattened = instance_kpts.flatten()
    keypoint_vectors.append(flattened)

    # Now keypoint_vectors is a list of 1D arrays, one per detected person/object
    # If you have multiple detections, you can select one or aggregate

    # Example: Use the first detected person's keypoints as input
if len(keypoint_vectors) > 0:
    input_keypoints = keypoint_vectors[0]  # 1D vector for first detected person
    print("Keypoint vector shape:", input_keypoints.shape)

       # You can now concatenate this with your ResNet features for Mamba input
else:
    print("No keypoints detected in this frame.")

tensor([[187.9316, 143.3364],
        [  0.0000,   0.0000],
        [175.0820, 131.1202],
        [  0.0000,   0.0000],
        [139.6472, 145.3846],
        [ 96.2096, 186.2070],
        [157.3366, 232.7977],
        [192.8087, 160.0798],
        [247.3005, 313.5802],
        [256.6579, 130.8009],
        [289.0013, 207.6659],
        [ 93.0947, 415.6727],
        [134.3389, 432.9201],
        [  0.0000,   0.0000],
        [  0.0000,   0.0000],
        [  0.0000,   0.0000],
        [  0.0000,   0.0000]], device='cuda:0')
Keypoint vector shape: torch.Size([34])


In [13]:
keypoints = results[0].keypoints.xy.flatten()

print(keypoints)

tensor([187.9316, 143.3364,   0.0000,   0.0000, 175.0820, 131.1202,   0.0000,   0.0000, 139.6472, 145.3846,  96.2096, 186.2070, 157.3366, 232.7977, 192.8087, 160.0798, 247.3005, 313.5802, 256.6579, 130.8009, 289.0013, 207.6659,  93.0947, 415.6727, 134.3389, 432.9201,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
          0.0000,   0.0000,   0.0000], device='cuda:0')


In [1]:
import os

In [2]:
os.listdir('/media/viplab/DATADRIVE1/driver_action_recognition/pose_resnet_features/A1')

['user_id_16080_5',
 'user_id_16700_5',
 'user_id_22640_5',
 'user_id_25077_7',
 'user_id_25432_7',
 'user_id_35418_5',
 'user_id_38159_7',
 'user_id_38479_5',
 'user_id_38479_7',
 'user_id_41850_5',
 'user_id_42711_7',
 'user_id_46141_7',
 'user_id_46844_5',
 'user_id_47158_5',
 'user_id_50347_7',
 'user_id_50921_7',
 'user_id_52046_5',
 'user_id_53307_5',
 'user_id_59014_7',
 'user_id_59581_5',
 'user_id_61962_5',
 'user_id_63764_5',
 'user_id_63764_7',
 'user_id_69039_5',
 'user_id_70176_7',
 'user_id_71720_7',
 'user_id_87903_5',
 'user_id_98067_5',
 'user_id_99882_7']